In [1]:
# Dependencies
import requests
import json
from pprint import pprint
import pandas as pd
import numpy as np

# Google developer API key
from config import API_KEY

In [2]:
# File to Load 
michelin_df = pd.read_csv("Resources/Michelin-Starred Restaurants.csv", encoding='utf-8')
michelin_df.head()

,Unnamed: 0,name,address,city,state,description,star,full_address,postal_code
0,1,Sushi Inoue,381 Lenox Ave,New York,NY,ONE STAR for this Japanese restaurant in Harlem.,1,"381 Lenox Ave, New York, NY 10027",10027
1,2,Dovetail,103 W 77th St,New York,NY,John Fraser's UWS fine dining restaurant has O...,1,"103 W 77th St, New York, NY 10024",10024
2,3,Cafe Boulud,20 E 76th St,New York,NY,Daniel Boulud's beloved Upper East Side restau...,1,"20 E 76th St, New York, NY 10021",10021
3,4,Jean-Georges,1 Central Park West,New York,NY,Jean-Georges Vongerichten's flagship restauran...,2,"1 Central Park West, New York, NY 10023",10023
4,5,Masa,10 Columbus Cir,New York,NY,Masa Takayama's pricey sushi restaurant has TH...,3,"10 Columbus Cir, New York, NY 10019",10019

In [3]:
# File to Load 
michelin_rev_df = pd.read_csv("Resources/michelin_rev_df.csv", encoding='utf-8')
michelin_rev_df.head()

,name,address,city,state,description,star,full_address,postal_code,Reservation platform
0,Sushi Inoue,381 Lenox Ave,New York,NY,ONE STAR for this Japanese restaurant in Harlem.,1,"381 Lenox Ave, New York, NY 10027",10027,Resy
1,Dovetail,103 W 77th St,New York,NY,John Fraser's UWS fine dining restaurant has O...,1,"103 W 77th St, New York, NY 10024",10024,NaN
2,Cafe Boulud,20 E 76th St,New York,NY,Daniel Boulud's beloved Upper East Side restau...,1,"20 E 76th St, New York, NY 10021",10021,OpenTable
3,Jean-Georges,1 Central Park West,New York,NY,Jean-Georges Vongerichten's flagship restauran...,2,"1 Central Park West, New York, NY 10023",10023,OpenTable
4,Masa,10 Columbus Cir,New York,NY,Masa Takayama's pricey sushi restaurant has TH...,3,"10 Columbus Cir, New York, NY 10019",10019,NaN

In [ ]:
michelin_rev_df.dtypes

In [ ]:
# michelin_rev_df.loc[michelin_rev_df["Reservation platform"]=='NaN']
michelin_rev_df['Reservation platform'].isnull().sum()

In [4]:
## Checking how to get a string of words from full_address
address = michelin_rev_df['full_address']
element = address[20].split(" ")
element

['13', 'E', '37th', 'St,', 'New', 'York,', 'NY', '10016']

In [10]:
## TESTING API RESPONSE ##
#base_url="https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=YOUR_API_KEY"

base_url = "https://maps.googleapis.com/maps/api/geocode/json?address="
api_key = f'&key={API_KEY}'

url = base_url+f'{element[0]}+{element[1]}+{element[2]}+{element[3]}+{element[4]}+{element[5]}+{element[6]}+{element[7]}'+api_key
# print(url)
response = requests.get(url).json()
pprint(response)

{'results': [{'address_components': [{'long_name': '13',
                                      'short_name': '13',
                                      'types': ['street_number']},
                                     {'long_name': 'East 37th Street',
                                      'short_name': 'E 37th St',
                                      'types': ['route']},
                                     {'long_name': 'Manhattan',
                                      'short_name': 'Manhattan',
                                      'types': ['political',
                                                'sublocality',
                                                'sublocality_level_1']},
                                     {'long_name': 'New York',
                                      'short_name': 'New York',
                                      'types': ['locality', 'political']},
                                     {'long_name': 'New York County',
                                      'short_name': 'New York County',
                                      'types': ['administrative_area_level_2',
                                                'political']},
                                     {'long_name': 'New York',
                                      'short_name': 'NY',
                                      'types': ['administrative_area_level_1',
                                                'political']},
                                     {'long_name': 'United States',
                                      'short_name': 'US',
                                      'types': ['country', 'political']},
                                     {'long_name': '10016',
                                      'short_name': '10016',
                                      'types': ['postal_code']}],
              'formatted_address': '13 E 37th St, New York, NY 10016, USA',
              'geometry': {'bounds': {'northeast': {'lat': 40.750223,
                                                    'lng': -73.9819748},
                                      'southwest': {'lat': 40.7500036,
                                                    'lng': -73.9821872}},
                           'location': {'lat': 40.7501259, 'lng': -73.9820676},
                           'location_type': 'ROOFTOP',
                           'viewport': {'northeast': {'lat': 40.75146228029151,
                                                      'lng': -73.9807320197085},
                                        'southwest': {'lat': 40.74876431970851,
                                                      'lng': -73.9834299802915}}},
              'place_id': 'ChIJUUovsgBZwokRD1GM2WrbAIQ',
              'types': ['premise']}],
 'status': 'OK'}

In [11]:
## TESTING API RESPONSE ##
response['results'][0]['geometry']['location']['lat']

40.7501259

In [12]:
# Testing how to add up all words of full_address in a string

adding_address = ""
adding = []
element = address[19].split(" ")
addresses = []

for j in range(len(element)):
        adding_address += f'{element[j]}+'
        adding = adding_address[:-1]


# len(element)
adding

'400+5th+Ave+#2,+New+York,+NY+10018'

In [14]:
base_url = "https://maps.googleapis.com/maps/api/geocode/json?address="


url = base_url+adding+api_key
response = requests.get(url).json()
pprint(response)
# latitude = response['results'][0]['geometry']['location']['lat']
# longitude = response['results'][0]['geometry']['location']['lng']
# lat.append(latitude)
# lon.append(longitude)
# print(f'Latitude: {latitude}')
# print(f'Longitude: {longitude}')
# print(michelin_rev_df['name'][19])

{'error_message': 'You must use an API key to authenticate each request to '
                  'Google Maps Platform APIs. For additional information, '
                  'please refer to http://g.co/dev/maps-no-account',
 'results': [],
 'status': 'REQUEST_DENIED'}

In [15]:
# Creating a list of the addresses in strings to feed the API request

addresses = []

for i in range(len(address)):
    element = address[i].split(" ")
    adding_address = ""
    adding = []
    for j in range(len(element)):
        adding_address += f'{element[j]}+'
        adding = adding_address[:-1]
    addresses.append(adding)

addresses

['381+Lenox+Ave,+New+York,+NY+10027',
 '103+W+77th+St,+New+York,+NY+10024',
 '20+E+76th+St,+New+York,+NY+10021',
 '1+Central+Park+West,+New+York,+NY+10023',
 '10+Columbus+Cir,+New+York,+NY+10019',
 '240+Central+Park+S,+New+York,+NY+10019',
 '60+E+65th+St,+New+York,+NY+10065',
 '362+W+53rd+St,+New+York,+NY+10019',
 '155+W+51st+St,+New+York,+NY+10019',
 '9+W+53rd+St,+New+York,+NY+10019',
 '65+E+55th+St,+New+York,+NY+10022',
 '538+Madison+Ave,+New+York,+NY+10022',
 '114+W+47th+St+(discreetly+located),+New+York,+NY+10036',
 '431+W+37th+St,+New+York,+NY+10018',
 '135+W+42nd+St,+New+York,+NY+10036',
 '41+W+42nd+St,+New+York,+NY+10036',
 '461+5th+Ave,+New+York,+NY+10017',
 '245+E+44th+St,+New+York,+NY+10017',
 '204+E+43rd+St,+New+York,+NY+10017',
 '400+5th+Ave+#2,+New+York,+NY+10018',
 '13+E+37th+St,+New+York,+NY+10016',
 '125+E+39th+St,+New+York,+NY+10016',
 '222+E+39th+St,+New+York,+NY+10016',
 '362+W+23rd+St,+New+York,+NY+10011',
 '16+W+29th+St,+New+York,+NY+10001',
 '1170+Broadway,+New+York,+NY+10001',
 '85+10th+Ave,+New+York,+NY+10011',
 '5-48+49th+Ave,+Long+Island+City,+NY+11101',
 '27+W+24th+St,+New+York,+NY+10010',
 '88+9th+Ave,+New+York,+NY+10011',
 '11+Madison+Ave,+New+York,+NY+10010',
 '5+Madison+Ave,+New+York,+NY+10010',
 '16+W+22nd+St,+New+York,+NY+10010',
 '126+W+18th+St,+New+York,+NY+10011',
 '641+Hudson+St,+New+York,+NY+10014',
 '31+W+17th+St,+New+York,+NY+10011',
 '42+E+20th+St,+New+York,+NY+10003',
 '52+Irving+Pl,+New+York,+NY+10003',
 '344+W+11th+St,+New+York,+NY+10014',
 '12+E+12th+St,+New+York,+NY+10003',
 '72+University+Pl,+New+York,+NY+10003',
 '110+Waverly+Pl,+New+York,+NY+10011',
 '75+Washington+Pl,+New+York,+NY+10011',
 '175+2nd+Ave,+New+York,+NY+10003',
 '113+Macdougal+St,+New+York,+NY+10012',
 '88+W+3rd+St,+New+York,+NY+10012',
 '181+Thompson+St,+New+York,+NY+10012',
 '169+Thompson+St,+New+York,+NY+10012',
 '239+E+5th+St,+New+York,+NY+10003',
 '94+E+7th+St,+New+York,+NY+10009',
 '8+Extra+Pl,+New+York,+NY+10003',
 '73+Thompson+St,+New+York,+NY+10012',
 '265+Elizabeth+St,+New+York,+NY+10012',
 '218+Bowery,+New+York,+NY+10012',
 '217+Eldridge+St,+New+York,+NY+10002',
 '7+Spring+St,+New+York,+NY+10012',
 '138+Orchard+St,+New+York,+NY+10002',
 '239+W+Broadway,+New+York,+NY+10013',
 '2+Harrison+St,+New+York,+NY+10013',
 '135+N+5th+St,+Brooklyn,+NY+11249',
 '77+Worth+St,+New+York,+NY+10013',
 '47+S+5th+St,+Brooklyn,+NY+11249',
 '225+Liberty+St,+New+York,+NY+10281',
 '149+Broadway,+Brooklyn,+NY+11211',
 '178+Broadway,+Brooklyn,+NY+11211',
 '436+Jefferson+St,+Brooklyn,+NY+11237',
 '261+Moore+St,+Brooklyn,+NY+11206',
 '1+Water+St,+Brooklyn,+NY+11201',
 '268+Clinton+St,+Brooklyn,+NY+11201',
 '212+Greene+Ave,+Brooklyn,+NY+11238',
 '4th+Floor++Time+Warner+Center++10+Columbus+Cir,+New+York,+NY+10023',
 'Grand+Central+Terminal++89+E+42nd+St,+New+York,+NY+10017']

In [16]:
# Fixing Ai Fiori's address
addresses[19] = addresses[19].replace('400+5th+Ave+#2,+New+York,+NY+10018', '400+5th+Ave,+New+York,+NY+10018') 
addresses[19]

'400+5th+Ave,+New+York,+NY+10018'

In [17]:
len(addresses)

72

In [18]:
# Performing the API requests and storing the coordinates in lists

lat =[]
lon = []

base_url = "https://maps.googleapis.com/maps/api/geocode/json?address="

for i in range(len(addresses)):
    try:
        print('===============')
        print(michelin_rev_df['name'][i])
        url = base_url+addresses[i]+"&key=AIzaSyA46ElldaT1niey5aBkvDRQ2DQCRSQgn9I"
        response = requests.get(url).json()
        latitude = response['results'][0]['geometry']['location']['lat']
        longitude = response['results'][0]['geometry']['location']['lng']
        lat.append(latitude)
        lon.append(longitude)
        print(f'Latitude: {latitude}')
        print(f'Longitude: {longitude}')
    except IndexError:
        print("There was a ERROR HERE!!!!!!!")
        continue

===============
 Sushi Inoue
Latitude: 40.8106508
Longitude: -73.94385799999999
===============
 Dovetail
Latitude: 40.7809576
Longitude: -73.9766017
===============
 Cafe Boulud
Latitude: 40.7744937
Longitude: -73.9640958
===============
 Jean-Georges
Latitude: 40.7690255
Longitude: -73.98162549999999
===============
 Masa
Latitude: 40.7685526
Longitude: -73.9831866
===============
 Marea
Latitude: 40.7674484
Longitude: -73.9811332
===============
 Daniel
Latitude: 40.7667727
Longitude: -73.9676284
===============
 Torishin
Latitude: 40.7649896
Longitude: -73.9871924
===============
 Le Bernardin
Latitude: 40.7615691
Longitude: -73.98180479999999
===============
 The Modern
Latitude: 40.7609475
Longitude: -73.9768318
===============
 Aquavit
Latitude: 40.760928
Longitude: -73.9721295
===============
 Caviar Russe
Latitude: 40.7607667
Longitude: -73.9738498
===============
 Satsuki (Suzuki’s sushi bar)
Latitude: 40.7581194
Longitude: -73.9830293
===============
 Chef's Table at Brooklyn Fare
Latitude: 40.7561226
Longitude: -73.9964617
===============
 Aureole
Latitude: 40.7555597
Longitude: -73.9853213
===============
 Gabriel Kreuther
Latitude: 40.7545381
Longitude: -73.98250260000002
===============
 Sushi Ginza Onodera
Latitude: 40.7521518
Longitude: -73.9814189
===============
 Sushi Amane
Latitude: 40.7516375
Longitude: -73.9717605
===============
 Sushi Yasuda
Latitude: 40.751119
Longitude: -73.9735049
===============
 Ai Fiori
Latitude: 40.7500752
Longitude: -73.9837835
===============
 Café China
Latitude: 40.7501259
Longitude: -73.9820676
===============
 Kajitsu
Latitude: 40.7498869
Longitude: -73.97769989999999
===============
 Tempura Matsui
Latitude: 40.7481306
Longitude: -73.9749707
===============
 Ushiwakamaru
Latitude: 40.746139
Longitude: -74.0010259
===============
 The Breslin
Latitude: 40.7456687
Longitude: -73.9880941
===============
 The NoMad Restaurant
Latitude: 40.7449561
Longitude: -73.9884704
===============
 Del Posto
Latitude: 40.7433097
Longitude: -74.0079322
===============
 Casa Enrique
Latitude: 40.7433938
Longitude: -73.95423509999999
===============
 Junoon
Latitude: 40.7431637
Longitude: -73.9908129
===============
 La Sirena
Latitude: 40.7423522
Longitude: -74.0040829
===============
 Eleven Madison Park
Latitude: 40.7416558
Longitude: -73.986845
===============
 The Clocktower
Latitude: 40.7412813
Longitude: -73.9873733
===============
 Cote Korean Steakhouse
Latitude: 40.7411848
Longitude: -73.99131299999999
===============
 Rouge Tomate Chelsea
Latitude: 40.7402203
Longitude: -73.9962661
===============
 Gunter Seeger NY
Latitude: 40.7390436
Longitude: -74.0057516
===============
 ALDEA
Latitude: 40.7387457
Longitude: -73.9937807
===============
 Gramercy Tavern
Latitude: 40.7384607
Longitude: -73.9885635
===============
 Casa Mono
Latitude: 40.7358936
Longitude: -73.9871361
===============
 Wallsé
Latitude: 40.7354249
Longitude: -74.00823559999999
===============
 Gotham Bar and Grill
Latitude: 40.734207
Longitude: -73.99369899999999
===============
 Nix
Latitude: 40.7332572
Longitude: -73.993611
===============
 Babbo
Latitude: 40.732296
Longitude: -73.9992785
===============
 Blue Hill
Latitude: 40.7320538
Longitude: -73.9996802
===============
 Kanoyama
Latitude: 40.7307062
Longitude: -73.98656629999999
===============
 Minetta Tavern
Latitude: 40.7299881
Longitude: -74.0007016
===============
 Sushi Zo
Latitude: 40.7298293
Longitude: -73.99917549999999
===============
 Carbone
Latitude: 40.72798909999999
Longitude: -74.0002311
===============
 ZZ's Clam Bar
Latitude: 40.72768540000001
Longitude: -74.0004606
===============
 Jewel Bako
Latitude: 40.7270133
Longitude: -73.9892383
===============
 Kyo Ya
Latitude: 40.7266497
Longitude: -73.9853787
===============
 Momofuku Ko
Latitude: 40.7248441
Longitude: -73.9916574
===============
 Hirohisa
Latitude: 40.7246381
Longitude: -74.0032315
===============
 The Musket Room
Latitude: 40.7239145
Longitude: -73.99381520000001
===============
 Rebelle
Latitude: 40.7219568
Longitude: -73.9937922
===============
 Uchu
Latitude: 40.721722
Longitude: -73.9902686
===============
 Uncle Boons
Latitude: 40.7213718
Longitude: -73.9943783
===============
 Contra
Latitude: 40.7198925
Longitude: -73.9890891
===============
 Bâtard
Latitude: 40.7194746
Longitude: -74.0057567
===============
 Jungsik
Latitude: 40.7188267
Longitude: -74.00907509999999
===============
 Delaware and Hudson
Latitude: 40.7170234
Longitude: -73.95910409999999
===============
 Atera
Latitude: 40.7169064
Longitude: -74.0055581
===============
 Aska
Latitude: 40.7124154
Longitude: -73.96652449999999
===============
 L'Appart
Latitude: 40.7120622
Longitude: -74.01516079999999
===============
 Meadowsweet
Latitude: 40.7104217
Longitude: -73.9631268
===============
 Peter Luger Steak House
Latitude: 40.7098013
Longitude: -73.9624977
===============
 Faro
Latitude: 40.70741599999999
Longitude: -73.9228274
===============
 Blanca
Latitude: 40.7050886
Longitude: -73.9335742
===============
 The River Café
Latitude: 40.7032009
Longitude: -73.9947318
===============
 La Vara
Latitude: 40.6878008
Longitude: -73.9957434
===============
 The Finch
Latitude: 40.686805
Longitude: -73.962869
===============
 Per Se
Latitude: 40.7685068
Longitude: -73.9831349
===============
 Agern
Latitude: 40.7527262
Longitude: -73.9772294

In [19]:
print(f'Length of lat is {len(lat)} and that of lon is {len(lon)}')

Length of lat is 72 and that of lon is 72

In [ ]:
print(lat)

In [ ]:
names = []

restaurants = michelin_rev_df['name']

for i in range(len(restaurants)):
    resto = restaurants[i]
    names.append(resto)

In [ ]:
address = []

for i in range(len(restaurants)):
    location = michelin_df['full_address'][i]
    address.append(location)

# address

In [ ]:
stars = []

for i in range(len(restaurants)):
    star = michelin_df['star'][i]
    stars.append(star)
    
stars = list(map(int, stars))

In [ ]:
data_set = {"restaurants": [names],
            "stars": [stars],
           "latitude": [lat], 
           "longitude": [lon],
           "address": [address]}

In [ ]:
json_dump = json.dumps(data_set)
print(json_dump)

In [ ]:
with open('./Resources/coordinates_good.json', 'w', encoding='utf-8') as f:
    json.dump(data_set, f, ensure_ascii=False, indent=4)

In [ ]:
from pprint import pprint

json_dump

In [ ]:
for i in range(len(restaurants)):
    print("{")
    print(f'"formatted_address" : "{address[i]}"'+",")
    print(f'"geometry" : '+ "{")
    print(f'  "location" :'+ "{")
    print(f'     "lat" : {lat[i]}' + ",")
    print(f'     "lon" : {lon[i]}')
    print("    } ")
    print("  }, ")
#     print(f'"michelin_stars" : "{stars[i]}"'+",")
    print(f'"name" : "{names[i]}"'+",")
    print("}, ")
    print(" ")

In [ ]:
import sys

orig_stdout = sys.stdout
f = open('Resources/the_one.txt', 'w')
sys.stdout = f

for i in range(len(restaurants)):
    print("{")
    print(f' "formatted_address" : "{address[i]}"'+",")
    print(f' "geometry" : '+ "{")
    print(f'   "location" :'+ " {")
    print(f'      "lat" : {lat[i]}' + ",")
    print(f'      "lng" : {lon[i]}')
    print("    } ")
    print("  }, ")
#     print(f'"michelin_stars" : "{stars[i]}"'+",")
    print(f' "name" : "{names[i]}"'+",")
    print("}, ")
    print(" ")

sys.stdout = orig_stdout
f.close()

In [ ]:
# with open("Resources/the_one.txt") as f:
#     json_dump = json.dumps(f, ensure_ascii=False, indent=4)

# print(json_dump)

In [ ]:
#### INTENDED RESULT #####

"results" : [
      {
         "formatted_address" : "1 Central Park West, New York, NY 10023, United States",
         "geometry" : {
            "location" : {
               "lat" : 40.769084,
               "lng" : -73.981431
            }
         },

         "name" : "Jean-Georges",
      },