In [1]:
import os
import requests
import json
from pprint import pprint
from api_key import api_key
import pandas as pd

In [2]:
# File to Load 
michelin_df = pd.read_csv("Resources/Michelin-Starred Restaurants.csv", encoding='utf-8')
michelin_df.head()

,Unnamed: 0,name,address,city,state,description,star,full_address,postal_code
0,1,Sushi Inoue,381 Lenox Ave,New York,NY,ONE STAR for this Japanese restaurant in Harlem.,1,"381 Lenox Ave, New York, NY 10027",10027
1,2,Dovetail,103 W 77th St,New York,NY,John Fraser's UWS fine dining restaurant has O...,1,"103 W 77th St, New York, NY 10024",10024
2,3,Cafe Boulud,20 E 76th St,New York,NY,Daniel Boulud's beloved Upper East Side restau...,1,"20 E 76th St, New York, NY 10021",10021
3,4,Jean-Georges,1 Central Park West,New York,NY,Jean-Georges Vongerichten's flagship restauran...,2,"1 Central Park West, New York, NY 10023",10023
4,5,Masa,10 Columbus Cir,New York,NY,Masa Takayama's pricey sushi restaurant has TH...,3,"10 Columbus Cir, New York, NY 10019",10019

In [3]:
# File to Load 
michelin_rev_df = pd.read_csv("Resources/michelin_rev_df.csv", encoding='utf-8')
michelin_rev_df.head()

,name,address,city,state,description,star,full_address,postal_code,Reservation platform
0,Sushi Inoue,381 Lenox Ave,New York,NY,ONE STAR for this Japanese restaurant in Harlem.,1,"381 Lenox Ave, New York, NY 10027",10027,Resy
1,Dovetail,103 W 77th St,New York,NY,John Fraser's UWS fine dining restaurant has O...,1,"103 W 77th St, New York, NY 10024",10024,NaN
2,Cafe Boulud,20 E 76th St,New York,NY,Daniel Boulud's beloved Upper East Side restau...,1,"20 E 76th St, New York, NY 10021",10021,OpenTable
3,Jean-Georges,1 Central Park West,New York,NY,Jean-Georges Vongerichten's flagship restauran...,2,"1 Central Park West, New York, NY 10023",10023,OpenTable
4,Masa,10 Columbus Cir,New York,NY,Masa Takayama's pricey sushi restaurant has TH...,3,"10 Columbus Cir, New York, NY 10019",10019,NaN

In [4]:
michelin_rev_df.dtypes

name                    object
address                 object
city                    object
state                   object
description             object
star                     int64
full_address            object
postal_code              int64
Reservation platform    object
dtype: object

In [7]:
# michelin_rev_df.loc[michelin_rev_df["Reservation platform"]=='NaN']
michelin_rev_df['Reservation platform'].isnull().sum()

43

In [ ]:
"""
Yelp Fusion API code sample.
This program demonstrates the capability of the Yelp Fusion API
by using the Search API to query for businesses by a search term and location,
and the Business API to query additional information about the top result
from the search query.
Please refer to http://www.yelp.com/developers/v3/documentation for the API
documentation.
This program requires the Python requests library, which you can install via:
`pip install -r requirements.txt`.
Sample usage of the program:
`python sample.py --term="bars" --location="San Francisco, CA"`
"""
from __future__ import print_function

import argparse
import json
import pprint
import requests
import sys
import urllib


# This client code can run on Python 2.x or 3.x.  Your imports can be
# simpler if you only need one of those.
try:
    # For Python 3.0 and later
    from urllib.error import HTTPError
    from urllib.parse import quote
    from urllib.parse import urlencode
except ImportError:
    # Fall back to Python 2's urllib2 and urllib
    from urllib2 import HTTPError
    from urllib import quote
    from urllib import urlencode


# Yelp Fusion no longer uses OAuth as of December 7, 2017.
# You no longer need to provide Client ID to fetch Data
# It now uses private keys to authenticate requests (API Key)
# You can find it on
# https://www.yelp.com/developers/v3/manage_app
API_KEY= None 


# API constants, you shouldn't have to change these.
API_HOST = 'https://api.yelp.com'
SEARCH_PATH = '/v3/businesses/search'
BUSINESS_PATH = '/v3/businesses/'  # Business ID will come after slash.


# Defaults for our simple example.
DEFAULT_TERM = 'dinner'
DEFAULT_LOCATION = 'San Francisco, CA'
SEARCH_LIMIT = 3


def request(host, path, api_key, url_params=None):
    """Given your API_KEY, send a GET request to the API.
    Args:
        host (str): The domain host of the API.
        path (str): The path of the API after the domain.
        API_KEY (str): Your API Key.
        url_params (dict): An optional set of query parameters in the request.
    Returns:
        dict: The JSON response from the request.
    Raises:
        HTTPError: An error occurs from the HTTP request.
    """
    url_params = url_params or {}
    url = '{0}{1}'.format(host, quote(path.encode('utf8')))
    headers = {
        'Authorization': 'Bearer %s' % api_key,
    }

    print(u'Querying {0} ...'.format(url))

    response = requests.request('GET', url, headers=headers, params=url_params)

    return response.json()


def search(api_key, term, location):
    """Query the Search API by a search term and location.
    Args:
        term (str): The search term passed to the API.
        location (str): The search location passed to the API.
    Returns:
        dict: The JSON response from the request.
    """

    url_params = {
        'term': term.replace(' ', '+'),
        'location': location.replace(' ', '+'),
        'limit': SEARCH_LIMIT,
        'attributes': 'reservation'
    }
    return request(API_HOST, SEARCH_PATH, api_key, url_params=url_params)


def get_business(api_key, business_id):
    """Query the Business API by a business ID.
    Args:
        business_id (str): The ID of the business to query.
    Returns:
        dict: The JSON response from the request.
    """
    business_path = BUSINESS_PATH + business_id

    return request(API_HOST, business_path, api_key)


def query_api(term, location):
    """Queries the API by the input values from the user.
    Args:
        term (str): The search term to query.
        location (str): The location of the business to query.
    """
    response = search(API_KEY, term, location)

    businesses = response.get('businesses')

    if not businesses:
        print(u'No businesses for {0} in {1} found.'.format(term, location))
        return

    business_id = businesses[0]['id']

    print(u'{0} businesses found, querying business info ' \
        'for the top result "{1}" ...'.format(
            len(businesses), business_id))
    response = get_business(API_KEY, business_id)

    print(u'Result for business "{0}" found:'.format(business_id))
    pprint.pprint(response, indent=2)


def main():
    parser = argparse.ArgumentParser()

    parser.add_argument('-q', '--term', dest='term', default=DEFAULT_TERM,
                        type=str, help='Search term (default: %(default)s)')
    parser.add_argument('-l', '--location', dest='location',
                        default=DEFAULT_LOCATION, type=str,
                        help='Search location (default: %(default)s)')

    input_values = parser.parse_args()

    try:
        query_api(input_values.term, input_values.location)
    except HTTPError as error:
        sys.exit(
            'Encountered HTTP error {0} on {1}:\n {2}\nAbort program.'.format(
                error.code,
                error.url,
                error.read(),
            )
        )

In [ ]:
results = search(api_key, 'Marea', location='new york')
results

In [ ]:
results['businesses'][0]['coordinates']['latitude']

In [ ]:
restaurants = michelin_df['name']
restaurants

In [ ]:
# for i in range(len(restaurants)):
#     print(f'{restaurants[i]}')

In [ ]:
results = search(api_key, 'Dovetail', location='new york')
latitude = results['businesses'][0]['coordinates']['latitude']

In [ ]:
lat = [];
lon = [];

for i in range(len(restaurants)):
    try: 
        results = search(api_key, f'{restaurants[i]}', location='new york')
        print('===========')
        print(f'{restaurants[i]}')
        latitude = results['businesses'][0]['coordinates']['latitude']
        longitude = results['businesses'][0]['coordinates']['longitude']
        print(f'latitude is {latitude}')
        print(f'longitude is {longitude}')
        lat.append(latitude)
        lon.append(longitude)
        print('===========')
    except IndexError:
        print('===========')
        print(f'{restaurants[i]} has a different response')
        latitude2 = results['region']['center']['latitude']
        longitude2 = results['region']['center']['longitude']
        print(f'latitude is {latitude2}')
        print(f'longitude is {longitude2}')
        lat.append(latitude2)
        lon.append(longitude2)
        print('===========')
        continue

In [ ]:
len(lat)

In [ ]:
names = []

for i in range(len(restaurants)):
    resto = restaurants[i]
    names.append(resto)

In [ ]:
address = []

for i in range(len(restaurants)):
    location = michelin_df['full_address'][i]
    address.append(location)

# address

In [ ]:
data_set = {"restaurants": [names],
           "latitude": [lat], 
           "longitude": [lon],
           "address": [address]}
# data_set

In [ ]:
json_dump = json.dumps(data_set)
print(json_dump)

In [ ]:
with open('./Resources/coordinates.json', 'w', encoding='utf-8') as f:
    json.dump(data_set, f, ensure_ascii=False, indent=4)

In [ ]:
from pprint import pprint

json_dump

In [ ]:
stars = []

for i in range(len(restaurants)):
    star = michelin_df['star'][i]
    stars.append(star)

# stars

In [ ]:
for i in range(len(restaurants)):
    print("{")
    print(f'"formatted_address" : "{address[i]}"'+",")
    print(f'"geometry" : '+ "{")
    print(f'  "location" :'+ "{")
    print(f'     "lat" : {lat[i]}' + ",")
    print(f'     "lon" : {lon[i]}')
    print("    } ")
    print("  }, ")
#     print(f'"michelin_stars" : "{stars[i]}"'+",")
    print(f'"name" : "{names[i]}"'+",")
    print("}, ")
    print(" ")

In [ ]:
"results" : [
      {
         "formatted_address" : "1 Central Park West, New York, NY 10023, United States",
         "geometry" : {
            "location" : {
               "lat" : 40.769084,
               "lng" : -73.981431
            }
         },

         "name" : "Jean-Georges",
      },